spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_online_store
    username: sehsekou98
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: sehsekou98
    password: password
    properties:
      mail:
        smtp:
          true: "*"
          auth: true
          starttls:
            enabled: true
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000
  security:
    oauth2:
      authorizationserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/Renee-smith-book-network"

application:

  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
